const facts = [
  "Bananas are berries, but strawberries are not.",
  "Octopuses have three hearts.",
  "A day on Venus is longer than a year on Venus.",
  "Wombats produce cube-shaped poop.",
  "Sharks existed before trees.",
  "The Eiffel Tower can grow taller in the summer due to heat expansion.",
  "Sloths can hold their breath longer than dolphins.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "A shrimp's heart is located in its head.",
  "There are more plastic flamingos than real ones in the United States.",
  "Scotland’s national animal is the unicorn.",
  "You can hear rhubarb grow in a quiet room.",
  "Honey never spoils.",
  "A group of flamingos is called a 'flamboyance'.",
  "Cows have best friends and get stressed when separated.",
  "Turtles can breathe through their butts.",
  "A cloud can weigh over a million pounds.",
  "Jellyfish are 95% water.",
  "There are more stars in the universe than grains of sand on Earth.",
  "The dot over a lowercase 'i' is called a tittle.",
  "The majority of your brain is fat.",
  "Koalas have fingerprints almost identical to humans.",
  "A single spaghetti noodle is called a 'spaghetto'.",
  "Some cats are allergic to humans.",
  "The smell of freshly-cut grass is a plant distress call.",
  "Sea otters hold hands when they sleep to avoid drifting apart.",
  "The shortest war in history lasted 38 to 45 minutes.",
  "Butterflies can taste with their feet.",
  "A group of porcupines is called a prickle.",
  "An apple floats in water because it’s 25% air.",
  "The inventor of the microwave received only $2 for his discovery.",
  "Mosquitoes are attracted to people who just ate bananas.",
  "The longest hiccuping spree lasted 68 years.",
  "Some frogs can be frozen solid and survive.",
  "Tigers have striped skin, not just striped fur.",
  "There’s a basketball court on the top floor of the U.S. Supreme Court building.",
  "Cows have four stomach compartments.",
  "The original Monopoly game was circular.",
  "Sponges don’t have brains, but they can still filter and respond to their environment.",
  "Some fish can cough.",
  "Octopuses taste with their arms.",
  "The heart of a blue whale is the size of a small car.",
  "Rain has a smell, and it's called petrichor.",
  "Elephants can recognize themselves in mirrors.",
  "The fingerprints of a koala are so close to humans' they can taint crime scenes.",
  "Humans share about 60% of their DNA with bananas.",
  "Snails can sleep for up to three years.",
  "The wood frog can survive being frozen.",
  "Rats laugh when tickled.",
  "A group of crows is called a murder."
]
export default facts
